app/adventext/play/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    #url(r'^$', views.CorePlayView.as_view()),
]

app/adventext/puzzle/urls.py
from django.conf.urls import url

from . import views
from . import views_events
from ..play.views import BuildTestView, BuildTestRestartView

urlpatterns = [
    url(r'^$', views.PuzzleBuildList.as_view(), name='build'),
    url(r'^create$', views.PuzzleCreate.as_view(), name='create'),

    # Puzzles
    url(r'^(?P<puzzle_pk>[0-9]+)/$', views.PuzzleBuildIndex.as_view(), name='index'),
    url(r'^(?P<puzzle_pk>[0-9]+)/edit/$', views.PuzzleBuildEdit.as_view(), name='edit'),
    url(r'^(?P<puzzle_pk>[0-9]+)/delete/$', views.PuzzleBuildDelete.as_view(), name='delete'),

    # Rooms
    url(r'^(?P<puzzle_pk>[0-9]+)/rooms/$', views.PuzzleBuildRoomList.as_view(), name='room_list'),
    url(r'^(?P<puzzle_pk>[0-9]+)/rooms/add/$', views.PuzzleBuildRoomCreate.as_view(), name='room_create'),
    url(r'^(?P<puzzle_pk>[0-9]+)/rooms/edit/(?P<room_pk>[0-9]+)/$', views.PuzzleBuildRoomUpdate.as_view(), name='room_update'),
    url(r'^(?P<puzzle_pk>[0-9]+)/rooms/delete/(?P<room_pk>[0-9]+)/$', views.PuzzleBuildRoomDelete.as_view(), name='room_delete'),

    # Room directions
    url(r'^(?P<puzzle_pk>[0-9]+)/directions/(?P<room_pk>[0-9]+)/$', views.PuzzleBuildDirectionList.as_view(), name='direction_list'),
    url(r'^(?P<puzzle_pk>[0-9]+)/directions/(?P<room_pk>[0-9]+)/add/$', views.PuzzleBuildDirectionCreate.as_view(), name='direction_create'),
    url(r'^(?P<puzzle_pk>[0-9]+)/directions/(?P<room_pk>[0-9]+)/edit/(?P<direction_pk>[0-9]+)/$', views.PuzzleBuildDirectionUpdate.as_view(), name='direction_update'),
    url(r'^(?P<puzzle_pk>[0-9]+)/directions/(?P<room_pk>[0-9]+)/delete/(?P<direction_pk>[0-9]+)/$', views.PuzzleBuildDirectionDelete.as_view(), name='direction_delete'),

    # Items
    url(r'^(?P<puzzle_pk>[0-9]+)/items/$', views.PuzzleBuildItemList.as_view(), name='item_list'),
    url(r'^(?P<puzzle_pk>[0-9]+)/items/add/$', views.PuzzleBuildItemCreate.as_view(), name='item_create'),
    url(r'^(?P<puzzle_pk>[0-9]+)/items/edit/(?P<item_pk>[0-9]+)/$', views.PuzzleBuildItemUpdate.as_view(), name='item_update'),
    url(r'^(?P<puzzle_pk>[0-9]+)/items/delete/(?P<item_pk>[0-9]+)/$', views.PuzzleBuildItemDelete.as_view(), name='item_delete'),

    # Interactions
    url(r'^(?P<puzzle_pk>[0-9]+)/interactions/$', views.PuzzleBuildInteractionList.as_view(), name='interaction_list'),
    url(r'^(?P<puzzle_pk>[0-9]+)/interactions/add/$', views.PuzzleBuildInteractionCreate.as_view(), name='interaction_create'),
    url(r'^(?P<puzzle_pk>[0-9]+)/interactions/edit/(?P<interaction_pk>[0-9]+)/$', views.PuzzleBuildInteractionUpdate.as_view(), name='interaction_update'),
    url(r'^(?P<puzzle_pk>[0-9]+)/interaction/delete/(?P<interaction_pk>[0-9]+)/$', views.PuzzleBuildInteractionDelete.as_view(), name='interaction_delete'),

    # Events
    url(r'^(?P<puzzle_pk>[0-9]+)/events/$', views_events.PuzzleBuildEventList.as_view(), name='event_list'),
    url(r'^(?P<puzzle_pk>[0-9]+)/events/add/$', views_events.PuzzleBuildEventCreate.as_view(), name='event_create'),
    url(r'^(?P<puzzle_pk>[0-9]+)/events/edit/(?P<event_pk>[0-9]+)/$', views_events.PuzzleBuildEventUpdate.as_view(), name='event_update'),
    url(r'^(?P<puzzle_pk>[0-9]+)/events/delete/(?P<event_pk>[0-9]+)/$', views_events.PuzzleBuildEventDelete.as_view(), name='event_delete'),
    url(r'^(?P<puzzle_pk>[0-9]+)/events/reorder/$', views_events.PuzzleBuildEventReorder.as_view(), name='event_reorder'),

    url(r'^(?P<puzzle_pk>[0-9]+)/events/manage/(?P<event_pk>[0-9]+)/$', views_events.PuzzleBuildEventManage.as_view(), name='event_manage'),
    url(r'^(?P<puzzle_pk>[0-9]+)/events/manage/(?P<event_pk>[0-9]+)/trigger/add/$', views_events.PuzzleBuildEventTriggerCreate.as_view(), name='event_trigger_create'),

    url(r'^(?P<puzzle_pk>[0-9]+)/events/trigger_info/(?P<trigger_pk>[a-z_0-9]+)/$', views_events.PuzzleBuildEventTriggerInfo.as_view(), name='event_trigger_info'),

    # Testing
    url(r'^(?P<puzzle_pk>[0-9]+)/test/$', BuildTestView.as_view(), name='test'),
    url(r'^(?P<puzzle_pk>[0-9]+)/test/restart/$', BuildTestRestartView.as_view(), name='test_restart'),

    ]

app/adventext/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

app/config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name="home"),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include("adventext.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    url(r'^play/', include("adventext.play.urls", namespace="play")),
    url(r'^puzzle/', include("adventext.puzzle.urls", namespace="puzzle")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request),
        url(r'^403/$', default_views.permission_denied),
        url(r'^404/$', default_views.page_not_found),
        url(r'^500/$', default_views.server_error),
    ]

app/adventext/play/models.py
from django.db import models
from adventext.puzzle.models import Puzzle
from adventext.users.models import User
from jsonfield import JSONField


class Quest(models.Model):
    """
    Quests are what link puzzles together that players go on.
    """
    difficulty_choices = (
          ('easy', 'Easy'),
          ('medium', 'Medium'),
          ('hard', 'Hard'),
        )
    quest_type_choices = (
          ('guest', 'Guest'),
          ('quest', 'Quest'),
          ('build', 'Build'),
          ('approve', 'Approve'),
        )

    user = models.ForeignKey(User, blank = True, null = True)
    quest_type = models.CharField(max_length = 16, choices = quest_type_choices)
    current_puzzle = models.ForeignKey(Puzzle, blank = True, null = True)
    difficulty = models.CharField(max_length = 16, choices = difficulty_choices)
    is_broken = models.BooleanField(default = 0)
    is_finished = models.BooleanField(default = 0)
    user_message = models.TextField()
    current_messages = JSONField()
    message_history = JSONField()


class QuestEntry(models.Model):
    """
    Each entry represents a puzzle that has been played
    on a particular quest.
    """
    class Meta:
        verbose_name_plural = "quest entries"

    quest = models.ForeignKey(Quest)
    puzzle = models.ForeignKey(Puzzle)


class QuestPuzzleStatus(models.Model):
    """
    This keeps track of state within a puzzle.
    Each action represents something to change from the
    base puzzle state with params telling it what to change.
    """
    class Meta:
        verbose_name_plural = "quest puzzle statuses"

    quest = models.ForeignKey(Quest)
    action_type = models.CharField(max_length = 255)
    key = models.TextField(default = "")
    param1 = models.TextField()
    param2 = models.TextField()
    param3 = models.TextField()
    param4 = models.TextField()
    param5 = models.TextField()



class PuzzlesCompleted(models.Model):
    """
    Every time a puzzle is played we put it here
    so players don't get repeated puzzles in quests.
    """
    class Meta:
        verbose_name_plural = "puzzles completed"

    user = models.ForeignKey(User)
    puzzle = models.ForeignKey(Puzzle)
    rating = models.FloatField()

app/adventext/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):
    name = models.CharField(_("Name of User"), blank=True, max_length=255)
    is_builder = models.BooleanField(_("Allowed to create puzzles"), default = False)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

    def can_build(self):
        return (self.is_builder or self.is_superuser())

app/adventext/play/views.py
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import TemplateView
from django.contrib import messages
from django.core.urlresolvers import reverse_lazy, reverse

from .quest import PuzzlePlayer, PuzzlePlayerValidationException
from .models import Quest
from ..puzzle.models import Puzzle
from ..puzzle.views import allowed_to_build_decorator


class PlayView(TemplateView):
    template_name = "play/test.html"
    redirects = {
        'serious_error' : reverse_lazy("index")
        }

    # PuzzlePlayer instance for this view
    puzzle_player = None

    # Puzzle model object to be played
    puzzle = None

    # Quest model object to be played
    quest = None

    # Set to True if it's the first time a puzzle is run
    starting_puzzle = False

    def get_puzzle_object(self):
        """Override to return the puzzle object from the DB for
        the current quest."""
        raise NotImplementedError

    def get_quest_object(self):
        """Override to return the quest object from the DB that
        will be played."""
        raise NotImplementedError

    def init_puzzle_player(self):
        self.puzzle_player = PuzzlePlayer(self.starting_puzzle, self.quest, self.puzzle)

    def init_view(self):
        try:
            self.quest = self.get_quest_object()
            self.puzzle = self.get_puzzle_object()
        except Puzzle.DoesNotExist:
            messages.success(self.request, "Requested puzzle does not exist.")
            return HttpResponseRedirect(self.redirects['serious_error'])
        self.init_puzzle_player()

    def dispatch(self, *args, **kwargs):
        r = self.init_view()
        if not r is None:
            return r
        return super(PlayView, self).dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        # catch dead puzzles and just render out without doing actions
        if self.quest.is_finished or self.quest.is_broken:
            # Catch the continue button
            if 'continue' in request.POST and request.POST['continue'] == "1":
                return self.continue_to_next_puzzle(request, *args, **kwargs)
            return self.render_to_response(self.get_context_data(**kwargs))

        action = None
        action_on = None
        # Determine if we are travelling
        if 'do_travel' in request.POST and \
               'travel' in request.POST and \
               request.POST['do_travel'] == "1" and \
               not request.POST['travel'] == "-1" :
            try:
                action_on = int(request.POST['travel'])
                action = "travel"
            except ValueError as e:
                messages.error(self.request, "Error travelling to passed room.")
                # TODO: Break quests
        # Or if we're doing an action
        elif 'do_action' in request.POST and \
                 'action' in request.POST and \
                 'item' in request.POST and \
                 request.POST['do_action'] == "1":
            action = request.POST['action']
            action_on = request.POST['item']
        # Only do the turn if there's an action to attend to
        if not action is None:
            try:
                self.puzzle_player.do_turn(action, action_on)
                return HttpResponseRedirect(request.get_full_path())
            except PuzzlePlayerValidationException as e:
                messages.warning(self.request, e)
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

    def continue_to_next_puzzle(self, request, *args, **kwargs):
        pass

    def get_context_data(self, **kwargs):
        context = super(PlayView, self).get_context_data(**kwargs)
        context['puzzle_player'] = self.puzzle_player
        context['quest'] = self.quest
        context['message_history'] = self.puzzle_player.history
        context['current_messages'] = self.puzzle_player.messages
        context['current_directions'] = self.puzzle_player.get_current_player_directions()
        context['current_room_items'] = self.puzzle_player.get_items_for_current_room()
        context['inventory'] = self.puzzle_player.get_items_in_inventory()
        context['interactions'] = []
        interactions = self.puzzle_player.get_current_player_interactions()
        for pk in list(interactions.keys()):
            single_interaction = interactions[pk].copy()
            single_interaction['pk'] = pk
            context['interactions'].append(single_interaction)
        return context


class BuildTestView(PlayView):
    template_name = "puzzle/build_test.html"
    redirects = {
        'serious_error' : reverse_lazy("puzzle:index")
        }

    def get_puzzle_object(self):
        return self.puzzle

    def get_quest_object(self):
        self.puzzle = Puzzle.objects.get(
            pk=self.kwargs['puzzle_pk'], author=self.request.user, approved=0
            )
        try:
            q = Quest.objects.get(
                quest_type="build",
                user=self.request.user,
                current_puzzle=self.puzzle
                )
        except Quest.DoesNotExist:
            q = Quest(
                quest_type="build",
                user=self.request.user,
                current_puzzle=self.puzzle
                )
            q.save()
            self.starting_puzzle = True
        return q

    @method_decorator(allowed_to_build_decorator)
    def dispatch(self, *args, **kwargs):
        return super(BuildTestView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(BuildTestView, self).get_context_data(**kwargs)
        context['puzzle'] = self.puzzle
        return context

    def continue_to_next_puzzle(self, request, *args, **kwargs):
        return HttpResponseRedirect(reverse("puzzle:test_restart", kwargs={'puzzle_pk':self.puzzle.pk}))


class BuildTestRestartView(BuildTestView):
    @method_decorator(allowed_to_build_decorator)
    def dispatch(self, *args, **kwargs):
        try:
            quest = self.get_quest_object()
        except Quest.DoesNotExist:
            return HttpResponseRedirect(reverse("puzzle:test"))
        puzzle = self.get_puzzle_object()
        quest.delete()
        messages.success(self.request, "Quest restarted.")
        return HttpResponseRedirect(reverse("puzzle:test", kwargs={'puzzle_pk':puzzle.pk}))

app/adventext/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from braces.views import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

app/adventext/templates/puzzle/build_event/event_create.html
{% extends "puzzle/base.html" %}

{% load common %}
{% load django_bootstrap_breadcrumbs %}
{% load crispy_forms_tags %}

{% block title %}Build Puzzles{% endblock %}

{% block breadcrumbs %}
  {{ block.super }}
  {% breadcrumb "Events" "puzzle:event_list" puzzle.pk %}
  {% breadcrumb "Add Event" "puzzle:event_create" puzzle.pk %}
{% endblock %}

{% block content %}
  {{ block.super }}
  <h2>Add Event</h2>
  <p>Here you can add a new event to your puzzle. Once you've chosen a name you'll be able to select triggers and actions for it.</p>
  {% crispy form %}
{% endblock %}

app/adventext/templates/puzzle/build_event/event_delete.html
{% extends "puzzle/base.html" %}

{% load common %}
{% load django_bootstrap_breadcrumbs %}

{% block title %}Build Puzzles{% endblock %}

{% block breadcrumbs %}
  {{ block.super }}
  {% breadcrumb "Events" "puzzle:event_list" puzzle.pk %}
  {% breadcrumb "Delete Event" "puzzle:event_delete" puzzle.pk item.pk %}
{% endblock %}

{% block content %}
  {{ block.super }}
  <h2>Delete Event</h2>

  <form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete the event "{{ object.name }}"?</p>
    <button type="submit" class="btn btn-secondary" />Confirm</button>
  </form>
{% endblock %}

app/adventext/templates/puzzle/build_event/event_list.html
{% extends "puzzle/base.html" %}

{% load staticfiles%}
{% load common %}
{% load django_bootstrap_breadcrumbs %}
{% load render_table from django_tables2 %}

{% block breadcrumbs %}
  {{ block.super }}
  {% breadcrumb "Events" "puzzle:event_list" puzzle.pk %}
{% endblock %}

{% block content %}
  {{ block.super }}
  <h2>Event</h2>
  <p>
    Events are where the real fun happens. Using them you can cause one or more actions to occur if the criteria for a set of triggers are met.
  </p>
  {% render_table table %}
  <p>
    <a href="{% url 'puzzle:event_create' puzzle.pk %}"  class="btn btn-primary-outline">Add Event</a>
  </p>
{% endblock %}

app/adventext/templates/puzzle/build_event/event_manage.html
{% extends "puzzle/base.html" %}

{% load staticfiles%}
{% load common %}
{% load django_bootstrap_breadcrumbs %}
{% load render_table from django_tables2 %}

{% block breadcrumbs %}
  {{ block.super }}
  {% breadcrumb "Events" "puzzle:event_list" puzzle.pk %}
  {% breadcrumb "Triggers & Actions" "puzzle:event_manage" puzzle.pk event.pk %}
{% endblock %}

{% block content %}
  {{ block.super }}
  <h2>Triggers</h2>
  <p>
    Triggers let you chose the criteria for the actions of an event to happen.
  </p>
  {% render_table tables.0 %}
  <p>
    <a href="{% url 'puzzle:event_trigger_create' puzzle.pk event.pk %}"  class="btn btn-primary-outline">Add Trigger</a>
  </p>

  <h2>Actions</h2>
  <p>
    Actions are what will happen when the criteria for all triggers have been satisfied.
  </p>
  {% render_table tables.1 %}
  <p>
    {# <a href="{% url 'puzzle:action_create' puzzle.pk event.pk %}"  class="btn btn-primary-outline">Add Action</a> #}
  </p>
{% endblock %}

app/adventext/templates/puzzle/build_event/event_trigger_action_description.html
<label class="control-label col-sm-2"> </label>
<div class="description_text controls col-sm-10">{{description}}</div>

app/adventext/templates/puzzle/build_event/event_trigger_create.html
{% extends "puzzle/base.html" %}

{% load common %}
{% load django_bootstrap_breadcrumbs %}
{% load crispy_forms_tags %}

{% block title %}Build Puzzles{% endblock %}

{% block breadcrumbs %}
  {{ block.super }}
  {% breadcrumb "Events" "puzzle:event_list" puzzle.pk %}
  {% breadcrumb "Add Event" "puzzle:event_create" puzzle.pk %}
  {% breadcrumb "Triggers & Actions" "puzzle:event_manage" puzzle.pk event.pk %}
  {% breadcrumb "Add Event Trigger" "puzzle:event_trigger_create" puzzle.pk event.pk %}
{% endblock %}

{% block content %}
  {{ block.super }}
  <h2>Add Event Trigger</h2>
  <p>Add a new trigger to this event. Once you select the type you will be able to select options for the trigger.</p>
  {% crispy form %}
{% endblock %}

app/adventext/templates/puzzle/build_event/event_update.html
{% extends "puzzle/base.html" %}

{% load common %}
{% load django_bootstrap_breadcrumbs %}
{% load crispy_forms_tags %}

{% block title %}Build Puzzles{% endblock %}

{% block breadcrumbs %}
  {{ block.super }}
  {% breadcrumb "Events" "puzzle:event_list" puzzle.pk %}
  {% breadcrumb "Edit Event" "puzzle:event_update" puzzle.pk item.pk %}
{% endblock %}

{% block content %}
  {{ block.super }}
  <h2>Edit Event</h2>
  {% crispy form %}
{% endblock %}